# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redoc.ly/docs/cli/ for more information.
TimeAddressableMediaStore.yaml:
  operation-summary:
    - '#/paths/~1/get/summary'
    - '#/paths/~1/head/summary'
    - '#/paths/~1service/get/summary'
    - '#/paths/~1service/post/summary'
    - '#/paths/~1service/head/summary'
    - '#/paths/~1sources/get/summary'
    - '#/paths/~1sources/head/summary'
    - '#/paths/~1flows/get/summary'
    - '#/paths/~1flows/head/summary'
    - '#/paths/~1flows~1{flowId}/get/summary'
    - '#/paths/~1flows~1{flowId}/put/summary'
    - '#/paths/~1flows~1{flowId}/delete/summary'
    - '#/paths/~1flows~1{flowId}/head/summary'
    - '#/paths/~1flows~1{flowId}~1storage/post/summary'
    - '#/paths/~1flows~1{flowId}~1segments/get/summary'
    - '#/paths/~1flows~1{flowId}~1segments/post/summary'
    - '#/paths/~1flows~1{flowId}~1segments/delete/summary'
    - '#/paths/~1flows~1{flowId}~1segments/head/summary'
    - '#/paths/~1flows~1{flowId}~1tags/get/summary'
    - '#/paths/~1flows~1{flowId}~1tags/head/summary'
    - '#/paths/~1flows~1{flowId}~1tags~1{name}/get/summary'
    - '#/paths/~1flows~1{flowId}~1tags~1{name}/put/summary'
    - '#/paths/~1flows~1{flowId}~1tags~1{name}/delete/summary'
    - '#/paths/~1flows~1{flowId}~1tags~1{name}/head/summary'
    - '#/paths/~1flows~1{flowId}~1description/get/summary'
    - '#/paths/~1flows~1{flowId}~1description/put/summary'
    - '#/paths/~1flows~1{flowId}~1description/delete/summary'
    - '#/paths/~1flows~1{flowId}~1description/head/summary'
    - '#/paths/~1flow-delete-requests/get/summary'
    - '#/paths/~1flow-delete-requests/head/summary'
    - '#/paths/~1flow-delete-requests~1{request-id}/get/summary'
    - '#/paths/~1flow-delete-requests~1{request-id}/head/summary'
  operation-4xx-response:
    - '#/paths/~1/get/responses'
    - '#/paths/~1/head/responses'
    - '#/paths/~1service/get/responses'
    - '#/paths/~1service/head/responses'
    - '#/paths/~1sources/get/responses'
    - '#/paths/~1sources/head/responses'
    - '#/paths/~1flows/get/responses'
    - '#/paths/~1flows/head/responses'
    - '#/paths/~1flows~1{flowId}/delete/responses'
    - '#/paths/~1flows~1{flowId}~1segments/get/responses'
    - '#/paths/~1flows~1{flowId}~1segments/delete/responses'
    - '#/paths/~1flows~1{flowId}~1segments/head/responses'
    - '#/paths/~1flows~1{flowId}~1tags/head/responses'
    - '#/paths/~1flows~1{flowId}~1tags~1{name}/delete/responses'
    - '#/paths/~1flows~1{flowId}~1description/delete/responses'
    - '#/paths/~1flow-delete-requests/get/responses'
    - '#/paths/~1flow-delete-requests/head/responses'
    - '#/paths/~1flow-delete-requests~1{request-id}/get/responses'
  no-unused-components:
    - '#/components/schemas/timestamp_type'
