name: CI Workflow
run-name: ${{ format('{0} triggered {1} on {2}', (github.event_name == 'workflow_dispatch' && format('User {0}', github.actor) || format('{0} event', github.event_name) ), github.workflow, github.ref) }}
on:
  schedule:
    - cron: '0 4 * * 1-5'

  push:

  workflow_dispatch:
    inputs:
      forceDocsUpload:
        description: 'Force API docs upload'
        required: true
        default: false
        type: boolean

jobs:
  CI:
    name: CI
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Lint specification
        run: make lint
        working-directory: ./api

      - name: Render API docs
        run: make render

      - name: Setup pages
        if: ${{ inputs.forceDocsUpload || ( github.ref == 'refs/heads/main' ) }}
        uses: actions/configure-pages@v3

      - name: Upload documentation artifact
        if: ${{ inputs.forceDocsUpload || ( github.ref == 'refs/heads/main' ) }}
        uses: actions/upload-pages-artifact@v2
        with:
          path: './api/docs'

  DeployPages:
    name: Deploy Pages
    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-22.04
    needs: CI
    if: ${{ inputs.forceDocsUpload || ( github.ref == 'refs/heads/main' ) }}
    steps:
      - name: Deploy documentation to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
      - name: Adding summary
        run: |
          echo "Documentation URL: ${{ steps.deployment.outputs.page_url }}" >> $GITHUB_STEP_SUMMARY
        